### PR TITLE
Fix email lesson ordering

### LINKED ISSUE #154: Lesson order in drip email is wrong for lessons within modules
To test:

- Create a course with some modules.
- Add some lessons to the modules.
- Reorder the lessons within the modules, and/or move lessons to other modules.
- Make all the lessons drip today, and manually run the `woo_scd_daily_cron_hook` cron task.
- You should see that the lessons are not ordered in the email the way they are ordered within the course.

### PR DESCRIPTION
**Pull request by gkaragia**
Fixes #154 

### Overview
Lessons can be ordered by two separate ways, by module or by lesson.
Previously, the lessons in the emails were only ordered if a lesson order was
defined and the module ordering was ignored. This is now fixed. Course ordering is not considered since we have no pages that display lessons from different courses. However the lessons that belong to the same course will be listed together.

### Testing
The automated tests for content drip are not configured to run at the moment. I spent some time trying to add a test and run it but unfortunately it proved to be a time consuming task so I skipped adding automated tests. 

Manual test cases that were executed:
- Ordering is correct when all lessons belong to a module.
- Ordering is correct when some lessons belong to modules.
- Ordering is correct when no lessons belong to a module.
- Lessons do not get mixed up when they belong to different courses.

To test the functionality follow the instructions outlined in #154

### CODE REVIEW

**Comment by donnapep** [comment]
@gkaragia I removed a couple of lessons from modules. They are ordered like so:
Screen Shot 2019-10-28 at 11 48 31 AM

But in the email the "Other Lessons" are ordered as per the following:
Screen Shot 2019-10-28 at 11 49 26 AM

In other words, "Other Lessons" are not ordered correctly in the email.

**Comment by gkaragia** [comment]
Hey @donnapep I have added extra logic to sort the lessons if they don't belong in a module so this should now work. 

There is still a chance for the 'Other lessons' to still not have the same ordering in case that they don't have the _order_$course_id meta set. The lessons that don't have this meta value are appended in the end with no particular order in both the frontend and the email ordering code. 
However, I don't think that there is a high chance to see that without deleting the values from the db manually as when you update the order in wp-admin it sets the '_order_$course_id' meta value for all lessons.

File: includes/class-scd-ext-drip-email.php [hunk 1]
```diff
@@ -399,14 +399,27 @@ private function get_ordered_courses_and_lessons( $lessons ) {
 
 		// Sort list of lessons for each course.
 		foreach ( $courses_and_lessons as $course_id => $lesson_data_items ) {
-			// Set the current order as the default just in case the course lesson order is not set
+
```
Comment (jom) [inline includes/class-scd-ext-drip-email.php]: We've been slowly removing the blank lines padding the inside of control structures. It exists all over the plugin still.

(Also in lines 410+412)

Comment (gkaragia) [reply includes/class-scd-ext-drip-email.php]: I am not sure if we should have rules about blank lines since I think that there can't be a guide which fits in every possible case. In most cases we should do what 'feels' right.

For example for what you suggest it might be ok in some of the cases but it could make the code hard to read in others. For example the code would start to feel cluttered if you had an if/else with 2-3 assignments in each branch and no blank lines or if you had nested if/else statements.

For the specifc case I can see no harm removing the blank line in 402 however removing lines in 410 and 412 I think it makes it a bit harder to read as the if/else together with the second if inside it makes it a bit too compact. What do you think?

Comment (donnapep) [reply includes/class-scd-ext-drip-email.php]: The problem with inconsistency in code styles is that it's quite subjective. While you might leave these blank lines in, someone else would likely come in later and remove them.

I would also argue that multiple `if/else` and nested `if` statements are themselves not very readable and can often be refactored to be more succinct and improve clarity.

Comment (gkaragia) [reply includes/class-scd-ext-drip-email.php]: I agree that many things in code styles are subjective. However what I am trying to say is that by introducing such a rule we actually lose clarity, at least for some of the cases, which defeats purpose.

If this rule has be decided already and is not subject to change, I am fine with removing the lines however do we have such decisions documented somewhere so I can be aware of them?

Comment (donnapep) [reply includes/class-scd-ext-drip-email.php]: > do we have such decisions documented somewhere so I can be aware of them?

Not to my knowledge.

**Comment by gkaragia** [comment]
@donnapep @jom should I proceed with merging?
